name: dsa_kit
description: "A scalable DSA utilities kit for Dart. Includes MinHeap, MaxHeap, and more."
version: 0.0.3
repository: https://github.com/Vishwa-Karthik/dsa_kit
homepage: https://github.com/Vishwa-Karthik/dsa_kit
issue_tracker: https://github.com/Vishwa-Karthik/dsa_kit/issues
license: MIT

environment:
  sdk: ">=3.2.0 <4.0.0"

platforms:
  android:
  ios:
  web:
  linux:
  macos:
  windows:

topics:
  - dsa
  - built-in-methods

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
